# Generated by CodiumAI
from cogs.schema import ChatbotAPIError
import pytest


class Test__Str__:

    #  Return the error message as a string.
    def test_return_error_message_as_string(self):
        error = ChatbotAPIError("Error message")
        assert str(error) == "Error message"

    #  Return the error message with the HTTP status code if it exists.
    def test_return_error_message_with_status_code(self):
        error = ChatbotAPIError("Error message", status_code=404)
        assert str(error) == "Error message (HTTP Status Code: 404)"

    #  Return the error message with the HTTP status code if it exists and is 0.
    def test_return_error_message_with_zero_status_code(self):
        error = ChatbotAPIError("Error message", status_code=0)
        assert str(error) == "Error message (HTTP Status Code: 0)"

    #  Return the error message with the HTTP status code if it exists and is negative.
    def test_return_error_message_with_negative_status_code(self):
        error = ChatbotAPIError("Error message", status_code=-500)
        assert str(error) == "Error message (HTTP Status Code: -500)"

    #  Return the error message with the response data if it exists.
    def test_return_error_message_with_response_data(self):
        error = ChatbotAPIError("Error message", response_data={"error": "Invalid input"})
        assert str(error) == "Error message"

    #  Return the error message with the HTTP status code and response data if they both exist.
    def test_return_error_message_with_status_code_and_response_data(self):
        error = ChatbotAPIError("Error message", status_code=500, response_data={"error": "Internal server error"})
        assert str(error) == "Error message (HTTP Status Code: 500)"
